apiVersion: v1
kind: Service
metadata:
  name: member-management-service
  namespace: member-management
spec:
  type: NodePort
  selector:
    app: member-management
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080