apiVersion: v1
kind: Secret
metadata:
  name: member-secret
  namespace: member-management
type: Opaque
stringData:
  DB_USERNAME: postgres
  DB_PASSWORD: password
  JWT_SECRET: my-super-secure-jwt-secret-key-256-bits-long!!
  JWT_EXPIRATION_MS: "3600000"
